[package]
name = "afl_fuzz"
version = "0.1.0"
edition = "2021"

[dependencies]
afl = "0.15.10"
arbitrary = { version = "1.3.2", features = ["derive"] }
tokio = { version = "1.39.2", features = ["full"] }

[dependencies.async_fuzzing_playbox]
path = "../fuzz_target"
